---
title: "Animated"
resource_files: config.yml
rmd_output_metadata:
  rsc_email_suppress_scheduled: yes
output:
  html_document:
    df_print: paged
  html_notebook: default
---



```{r setup, include = FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, comment = NA)
library(tidyverse)
library(tidyquant)
library(timetk)
library(highcharter)
library(blastula)
library(formattable)
library(openxlsx)
library(config)
library(dbplyr)
library(DBI)
library(odbc)
library(htmltools)

dw <- config::get("mssql")

con <- DBI::dbConnect(odbc::odbc(),
                      Driver = dw$Driver,
                      Server = dw$Server,
                      #Host = dw$Host,
                      UID    = dw$UID,
                      PWD    = dw$PWD,
                      Port   = dw$Port,
                      Database = dw$Database
                      #Schema = dw$Schema
                      )

```

### Import data from sql

```{r}
bls_labor_for_data <-
  tbl(con, "bls_labor_for_data") %>% 
  collect() %>% 
  mutate(date = ymd(date),
         value = as.numeric(value))

```


```{r}
library(gganimate)

anim <- 
  ggplot(bls_labor_for_data, aes(x = date, y =  value, color = dem, label = dem)) +
  geom_line() +
  transition_reveal(date)
  #geom_text(size = 5) +
  # theme_minimal(base_size=20)+ #use minimal theme from ggthemes library
  # 
  # theme(plot.title=element_text())+theme(plot.caption=element_text(hjust=0,vjust=1,margin=margin(t=10)))+
  # theme(plot.margin=unit(c(0.25,0.25,0.25,0.25),"cm"))+
  # scale_x_date(date_breaks="2 years",date_labels="%Y")+
  # coord_cartesian(xlim=c(as.Date("2003-01-01"),as.Date("2018-12-31")))+
  # scale_y_continuous(limits=c(0,1.5),breaks=seq(0,1.5,.25))+
  # theme(legend.position="none")+
  # labs(title="Household debt balances",
  #      subtitle="Trillions of Dollars",
  #      x="",y="",caption="@lenkiefer Source: FRBNY Consumer Credit Panel/Equifax through 2018Q3")  +
  

# use end_pause=20 to hold last frame for 20 frames (~2 seconds)
animate(anim, end_pause=20,width=800,height=600)
anim_save(file="credit18Q3.gif", animation = last_animation())
```


