---
title: "R Notebook"
output: html_notebook
---

```{r setup}
library(tidyverse) 
library(rvest)     
library(lubridate)    
```


```{r}

etf_closures_url <- "https://www.etf.com/etf-watch-tables/etf-closures"

etf_closures_html <- read_html(etf_closures_url)

etf_closures_tibble <-
etf_closures_html  %>% 
    html_nodes(xpath = '//*[@id="article-body-content"]/table') %>%
  html_table(fill = TRUE) %>% 
    .[[1]] %>%
    rename(close_date = X1, fund = X2, ticker = X3) %>% 
    slice(-1:-2) %>% 
    filter(!(ticker == "Source: FactSet") | !(nchar(close_date) < 2)) %>% 
    filter(!(ticker %in% c("2019", "2018", "2017", "2016"))) %>% 
    mutate(close_date = str_replace(close_date, "20177", "2017"),
        ticker = case_when(nchar(fund) < 8 ~ fund,
                                          TRUE ~ ticker),
           fund = case_when(nchar(close_date) > 10 ~ close_date,
                                          TRUE ~ fund),
           close_date = case_when(between(nchar(close_date), 3, 10) ~ close_date)) %>%
    fill(close_date) %>% 
    filter(nchar(fund) > 4) %>% 
    mutate(close_date = case_when(nchar(close_date) > 4 ~ lubridate::ymd(lubridate::parse_date_time(close_date, "%m/%d/%Y")),
                                  nchar(close_date) == 4 ~ lubridate::ymd(close_date, truncated = 2L) + months(6)))
           
```



```{r}
etf_closures_tibble %>% 
  head()
```



```{r}


etf_launches_url <- "https://www.etf.com/etf-watch-tables/etf-launches"


etf_launches_html <- read_html(etf_launches_url)


etf_launches_html  %>% 
    html_nodes(xpath = '//*[@id="article-body-content"]/table[1]') %>%
  html_table(fill = TRUE) %>% 
    .[[1]] %>% 
        rename(date = X1, Fund = X2, Ticker = X3) %>% 
    slice(-1)

etf_launches_scraper_fun <- function(table = 1){
    xpath = paste('//*[@id="article-body-content"]/table[', table, ']', sep = "")
    
    etf_launches_html  %>% 
        html_nodes(xpath = xpath) %>%
        html_table(fill = TRUE) %>% 
        .[[1]] %>% 
        rename(launch_date = X1, fund = X2, ticker = X3, exchange = X4) %>% 
        slice(-1) %>% 
        mutate(launch_date = lubridate::ymd(lubridate::parse_date_time(launch_date, "%m/%d/%Y")))
}

etf_launches_tibble <- 
map_dfr(1:8, etf_launches_scraper_fun)
```


```{r}
etf_launches_tibble %>% 
    left_join(etf_closures_tibble %>% select(-fund), by = "ticker") %>% 
    select(launch_date, close_date, ticker, fund) %>% 
    filter(!is.na(close_date) & close_date > launch_date) %>% 
    mutate(survival_time = close_date - launch_date) %>% 
    arrange(desc(survival_time))
    
```

```{r}
etf_launches_tibble %>% 
    left_join(etf_closures_tibble %>% select(-fund), by = "ticker") %>% 
    select(launch_date, close_date, ticker, fund) %>% 
    filter(!is.na(close_date) & close_date > launch_date) %>% 
    mutate(survival_time = close_date - launch_date) %>% 
    arrange(desc(survival_time)) %>% 
  mutate(launch_year = year(launch_date))
```

```{r}
chosen_year <- 2014

etf_launch_close_tibble <- 
etf_launches_tibble %>% 
    left_join(etf_closures_tibble %>% select(-fund), by = "ticker") %>% 
    select(launch_date, close_date, ticker, fund) %>% 
    filter(!is.na(close_date) & close_date > launch_date) %>% 
    mutate(survival_time = close_date - launch_date) %>% 
    # arrange(desc(survival_time)) %>% 
  mutate(launch_year = year(launch_date)) %>% 
  group_by(launch_year) %>% 
  mutate(rank = rank(-survival_time)) #%>%
  #group_by(company) %>%
  # filter(rank <= 20) %>%
  # ungroup()

write_rds(etf_launch_close_tibble, "etf_launch_close_tibble.RDS")
library(gganimate)
etf_launch_close_tibble %>% 
  top_n(-10, survival_time) %>%
  filter(launch_year != 2019) %>% 
  group_by(launch_year) %>% 
  #slice(1:10) %>% 
  ggplot(aes(x = rank, group = ticker, fill = ticker, color = ticker)) +
  #geom_bar(stat='identity', width = .7) +
  geom_tile(aes(y = survival_time/2, height = survival_time, width = 0.9,
            alpha = 0.8, color = ticker)) +
  geom_text(aes(y = 0, label = paste(ticker, " ")), vjust = 0.2, hjust = 1, size = 7) +
  geom_text(aes(y = survival_time, label = ticker, hjust = 0), size = 7) +
  # aes(x = rank, group = company, fill = company, color = company) +
  # geom_tile(aes(y = revenue/2, height = revenue, width = 0.9),
  #           alpha = 0.8, color = NA) +
  #
  #coord_flip() +
  # geom_text(
  #   aes(label = survival_time,
  #       y = survival_time/2),
  #   color = "white",
  #   size = 5,
  #   hjust = 1
  # )  +
  coord_flip() +
  cowplot::theme_minimal_vgrid(16) +
    ylab("days survived") +
  guides(color = FALSE, fill = FALSE) +
  theme(
    axis.title.y = element_blank(), 
    legend.position = "none"
  )  +
  transition_states(launch_year, transition_length = 12, state_length = 8, wrap = FALSE)
```


```{r}
url <- "https://en.wikipedia.org/wiki/List_of_largest_biomedical_companies_by_revenue"

revenue_table <- read_html(url) %>%
  html_node("table") %>%
  html_table(fill = TRUE)

colnames(revenue_table)[3:ncol(revenue_table)] <- c("company", 2019:2011)

revenue <- tidyr::pivot_longer(
  data = revenue_table[, 3:ncol(revenue_table)],
  cols = `2019`:`2011`,
  names_to = "year",
  names_ptypes = list(year = integer()),
  values_to = "revenue"
)

revenue <- within(revenue, {
  revenue[revenue %in% c("", "–")] <- NA

  revenue <- stringr::str_remove(
    string = revenue,
    pattern = "Q[1-3]\\[[0-9]+\\]|\\[[0-9]+\\]"
  ) %>% trimws() %>% as.numeric()

  company_name_end <<- stringr::str_locate(
    string = company,
    pattern = "Private|[[:upper:]]{3,}:"
  )[, 1]

  company <- substr(company, 1, company_name_end - 1L)
})

### Animation ###
library(dplyr)
library(ggplot2)
library(gganimate)

revenue_formatted <- revenue %>%
  group_by(year) %>%
  mutate(revenue_with_jitter = jitter(revenue),
         rank = rank(-revenue_with_jitter),
         label = paste0(" $", revenue, " Bn.")) %>%
  group_by(company) %>%
  filter(rank <= 20) %>%
  ungroup()

static_plot <- ggplot(revenue_formatted) +
  aes(x = rank, group = company, fill = company, color = company) +
  geom_tile(aes(y = revenue/2, height = revenue, width = 0.9),
            alpha = 0.8, color = NA) +
  geom_text(aes(y = 0, label = paste(company, " ")), vjust = 0.2, hjust = 1, size = 7) +
  geom_text(aes(y = revenue, label = label, hjust = 0), size = 7) +
  coord_flip(clip = "off", expand = FALSE) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_reverse() +
  guides(color = FALSE, fill = FALSE) +
  theme(axis.line = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.position = "none",
        panel.background = element_blank(),
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_line(size = .1, color = "grey"),
        panel.grid.minor.x = element_line(size = .1, color = "grey"),
        plot.title = element_text(size = 25, hjust = 0.5, face = "bold",
                                  colour = "grey", vjust = 0),
        plot.background = element_blank(),
        plot.margin = margin(2, 4, 2, 11, "cm"))

animation <- static_plot +
  transition_states(year, transition_length = 12, state_length = 8, wrap = FALSE) +
  view_follow(fixed_x = TRUE, fixed_y = TRUE)  +
  labs(title = "Year: {closest_state}")
```


